name: Publish Python on TestPyPi

on:
  push:
    branches:
      - dev

jobs:
  build-n-publish:
    name: Publish Python on TestPyPi
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@dev
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install pep517
        run: >-
          python -m pip install pep517 --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m pep517.build --source --binary --out-dir dist/

      - name: Publish distribution to Test PyPi
        if: startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@dev
        with:
          repository_url: https://test.pypi.org/legacy/
          pass: ${{ secrets.pypi_test_password }}
